language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install python-coveralls"
  - "pip install coverage"
  - "pip install nose"

# command to run tests
script:
  - nosetests --with-coverage
after-success:
  - coveralls
